version: '3'

services:
  mongo:
    image: mongo
    container_name: nestjs_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
  api:
    image: test-nest-api:latest
    container_name: test-api
    restart: always
    ports:
      - "3000"
